version: '3.8'

services:
  app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    # Enable debugging port
    ports:
      - "3000:3000"
      - "9229:9229"  # For debugging if needed
